### ISSUE TITLE
Crash with node label and -u

### ISSUE THREAD

**Issue by towolf** [robscott/kube-capacity#19]
```
$ kube-capacity  --node-labels 'kubernetes.io/hostname=h1349' -u
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10cf0c5]

goroutine 1 [running]:
github.com/robscott/kube-capacity/pkg/capacity.buildClusterMetric(0xc00028a9a0, 0xc0013a0700, 0xc00028a380, 0xc001464150, 0x0, 0x1c, 0x0)
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/capacity/resources.go:97 +0x4c5
github.com/robscott/kube-capacity/pkg/capacity.FetchAndPrint(0x1010000, 0x0, 0x0, 0x7fff578efb99, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x136a805, ...)
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/capacity/capacity.go:53 +0x286
github.com/robscott/kube-capacity/pkg/cmd.glob..func1(0x20ca900, 0xc00043c300, 0x0, 0x3)
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/cmd/root.go:49 +0x21d
github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra.(*Command).execute(0x20ca900, 0xc0000be010, 0x3, 0x3, 0x20ca900, 0xc0000be010)
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x20ca900, 0xc00043bf68, 0x10e5cae, 0x20ca900)
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra/command.go:800
github.com/robscott/kube-capacity/pkg/cmd.Execute()
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/cmd/root.go:79 +0x32
main.main()
        /usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/main.go:22 +0x20

$ kube-capacity  version
kube-capacity version 0.3.2
```

**Comment by towolf** [comment]
`kube-capacity  --node-labels kubernetes.io/hostname=h1349 -p` works

**Comment by mitchellmaler** [comment]
Just ran into this same issue.

**Comment by robscott** [comment]
Hey @towolf and @mitchellmaler thanks for reporting this issue! Sorry I'd missed this earlier. Hopefully I'll get some time next week to take a look at this.
